version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: saldo_seguro
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=saldo_seguro_database
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
